version: "3.8"
services:
  api-gateway:
    container_name: api_gateway_container
    build:
      context: ./api-gateway
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 4000:4000
    env_file: ./api-gateway/src/configs/.env.development
    environment:
      - DOCKER_ENV=true
      - PRODUCT_SERVICE_URL=http://product-service:4001
      - AUTH_SERVICE_URL=http://auth-service:4002
    volumes:
      - ./api-gateway/src:/app/src # HOT RELOADING
  product-service:
    container_name: product_service_container
    build:
      context: ./product-service
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 4001:4001
    env_file: ./product-service/src/configs/.env.development
    environment:
      - DOCKER_ENV=true
      - PRODUCT_SERVICE_URL=http://product-service:4001
      - AUTH_SERVICE_URL=http://auth-service:4002
    volumes:
      - ./product-service/src:/app/src # HOT RELOADING
  auth-service:
    container_name: auth_service_container
    build:
      context: ./auth-service
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 4002:4002
    env_file: ./auth-service/src/configs/.env.development
    environment:
      - DOCKER_ENV=true
      - PRODUCT_SERVICE_URL=http://product-service:4001
      - AUTH_SERVICE_URL=http://auth-service:4002
    volumes:
      - ./auth-service/src:/app/src # HOT RELOADING
