version: "3.8"
services:
  product_app:
    container_name: user_service_app
    build:
      context: ./product-service
      dockerfile: Dockerfile.local
    restart: always
    ports:
      - 4001:4001
    env_file: ./product-service/src/configs/.env.development
    environment:
      - DOCKER_ENV=true
  auth_app:
    container_name: auth_service_app
    build:
      context: ./auth-service
      dockerfile: Dockerfile.local
    restart: always
    ports:
      - 4002:4002
    env_file: ./auth-service/src/configs/.env.development
    environment:
      - DOCKER_ENV=true
