FROM node:20-alpha3.19 as builder
WORKDIR /app

COPY package.json ./

RUN npm install && npm install -g nodemon

COPY build-script.js ./
COPY ecosystem.config.js ./
COPY tsconfig.json ./
COPY nodemon.json ./
COPY src ./src
COPY tsoa.json ./

RUN npm run build

FROM node:20-alpha3.19

WORKDIR /app

COPY package.json ./
RUN npm install --only=production

COPY --from=builder /app/build/ .

EXPOSE 4003

CMD [ "node","server.js" ]
